# Generated by Django 4.2.30 on 2026-06-03 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('no_iniciado', 'No Iniciado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado')], default='no_iniciado', max_length=20, verbose_name='Estado')),
                ('tipo', models.CharField(choices=[('abierto', 'Abierto al Público'), ('control_entradas', 'Control de Entradas')], max_length=20, verbose_name='Tipo')),
                ('link_formulario', models.URLField(blank=True, verbose_name='Link Formulario de Inscripción')),
                ('municipio', models.CharField(max_length=100, verbose_name='Municipio')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('detalles_ubicacion', models.TextField(blank=True, verbose_name='Detalles de Ubicación')),
                ('horario', models.TimeField(verbose_name='Horario')),
                ('geolocalizacion', models.CharField(blank=True, max_length=255, verbose_name='Geolocalización (lat,lng)')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='eventos.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EventoFlyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='eventos/flyers/', verbose_name='Archivo')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('video', 'Video')], default='imagen', max_length=10, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flyers', to='eventos.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Flyer de Evento',
                'verbose_name_plural': 'Flyers de Eventos',
            },
        ),
    ]
