# Generated by Django 4.2.30 on 2026-06-03
from django.db import migrations
from django.contrib.auth.models import Group


def crear_grupos_y_asignar(apps, schema_editor):
    """Crear grupos Gestor y Moderador."""
    grupo_gestor, _ = Group.objects.get_or_create(name='Gestor')
    grupo_moderador, _ = Group.objects.get_or_create(name='Moderador')

    # Sincronizar is_moderador de usuarios existentes hacia el grupo
    Usuario = apps.get_model('usuarios', 'Usuario')
    for usuario in Usuario.objects.filter(is_moderador=True):
        usuario.groups.add(grupo_moderador)


def reverse_migration(apps, schema_editor):
    Group.objects.filter(name__in=['Gestor', 'Moderador']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(crear_grupos_y_asignar, reverse_migration),
    ]
