# Generated by Django 4.2.30 on 2026-06-03 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario'),
        ),
        migrations.AddField(
            model_name='message',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Remitente'),
        ),
        migrations.AddField(
            model_name='calification',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='eventos.evento', verbose_name='Evento'),
        ),
        migrations.AddField(
            model_name='calification',
            name='gestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Gestor'),
        ),
        migrations.AddConstraint(
            model_name='calification',
            constraint=models.UniqueConstraint(fields=('gestor', 'evento'), name='unique_calification_per_gestor_evento'),
        ),
    ]
