# Generated by Django 4.2.30 on 2026-06-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='leido',
            field=models.BooleanField(default=False, verbose_name='¿Leído?'),
        ),
        migrations.AddField(
            model_name='message',
            name='room_identifier',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Identificador de sala'),
        ),
    ]
